export const FETCH_WORKS = 'FETCH_WORKS';
export const FETCH_WORKS_SUCCESS = 'FETCH_WORKS_SUCCESS';
export const FETCH_WORKS_FAILED = 'FETCH_WORKS_FAILED';

export const ADD_WORKS = 'ADD_WORKS';

export const FILTER_WORKS = "FILTER_WORKS";
export const FILTER_WORKS_SUCCESS = "FILTER_WORKS_SUCCESS";
export const FILTER_WORKS_FAILED = "FILTER_WORKS_FAILED";
