export const FETCH_WORKS = 'FETCH_WORKS';
export const FETCH_WORKS_SUCCESS = 'FETCH_WORKS_SUCCESS';
export const FETCH_WORKS_FAILED = 'FETCH_WORKS_FAILED';

export const FILTER_WORKS = "FILTER_WORKS";
export const FILTER_WORKS_SUCCESS = "FILTER_WORKS_SUCCESS";
export const FILTER_WORKS_FAILED = "FILTER_WORKS_FAILED";
export const ADD_WORKS = 'ADD_WORKS';
export const ADD_WORK_SUCCESS = 'ADD_WORK_SUCCESS';

export const EDIT_WORKS = 'EDIT_WORKS';
export const UPDATE_WORKS = 'UPDATE_WORKS';
export const UPDATE_WORK_SUCCESS = 'UPDATE_WORK_SUCCESS';

export const DELETE_WORKS = 'DELETE_WORKS';
export const DELETE_WORK_SUCCESS = 'DELETE_WORK_SUCCESS';

export const UPDATE_STATUS = 'UPDATE_STATUS';
export const UPDATE_STATUS_SUCCESS = 'UPDATE_STATUS_SUCCESS';

